version: "3"

services:
  db:
    image: postgres:14.1-alpine
    ports:
      - 5433:5432
    container_name: trpc-ssr
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trpc-ssr
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data_container:/var/lib/postgresql/data
volumes:
  postgres_data_container:
    driver: local
